### ISSUE TITLE
Hardware Research & Selection

### ISSUE THREAD

**Issue by cjhr95** [MissouriMRR/SUAS-2025#10]
# Hardware Research  & Selection

## Problem

We need to decide on a mechanism for obstacle detection and avoidance.

## Solution

Research low cost LiDAR solution, or attempt to fix the current ultrasonic sonar sensors, using the code and knowledge from SUAS 2024.

## Additional Information

If investigating LiDARS, look into cheaper solutions. $5000 Ouster LiDARs will not work,

**Comment by DJDMVP** [comment]
Current Decision from SUAS rules is that we do not need a lidar due to drone paths not crossing. If plans change and we need a back up We plan to use [this lidar](https://www.amazon.com/Slamtec-A2M12-Intelligent-Avoidance-Education/dp/B0B44PQZN7) and just use ardupilot firmaware to interact with it.
